version: "3.9"
services:
  db:
    image: postgres:16
    container_name: ids706_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  pgdata:
